version: "3.9"

services:
  bot-telegram:
    build:
      context: ./
      dockerfile: ./Dockerfile.yml
    restart: always
    container_name: bot-telegram
    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.bot-telegram.rule=Host(`${DOMAIN_TELEGRAM_BITCOINWORLD}`)
      - traefik.http.routers.bot-telegram.entrypoints=web
      - traefik.http.routers.bot-telegram.middlewares=bot-redirect
      - traefik.http.routers.bot-telegram-secure.rule=Host(`${DOMAIN_TELEGRAM_BITCOINWORLD}`)
      - traefik.http.routers.bot-telegram-secure.entrypoints=websecure
      - traefik.http.routers.bot-telegram-secure.tls.certresolver=letsencrypt
      - traefik.http.routers.bot-telegram-secure.service=bot-telegram
      # Services
      - traefik.http.services.bot-telegram.loadbalancer.server.port=${INSIDE_APP_PORT}
      # Redirect scheme
      - traefik.http.middlewares.bot-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.bot-redirect.redirectscheme.permanent=true
    ports:
      - 0.0.0.0:${OUTSIDE_APP_PORT}:${INSIDE_APP_PORT}
    networks:
      - traefik

  traefik:
    image: "traefik:v2.9.1"
    restart: always
    container_name: traefik
    command:
      - --log.level=INFO
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.watch=false
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # TLS
      - --certificatesresolvers.letsencrypt.acme.email=${EMAIL_CERT}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      # Access Logs
      - --accesslog=true
      - --accesslog.filepath=/traefik/access.log
      - --accesslog.format=json
      - --accesslog.bufferingsize=100
      - --accesslog.filters.statuscodes="200,304,400-404"
      - --accessLog.filters.retryAttempts=true
      - --accesslog.filters.minduration=10ms
      # Health Check
      - --ping=true
    environment:
      - TZ=Asia/Bangkok
    healthcheck:
      test: ['CMD', 'traefik', 'healthcheck', '--ping']
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik

networks:
  traefik:
    external: true